version: "3.3"
services:
  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
  bot:
    environment:
      MONGO_URI: "mongodb://mongo:27017/betting"
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"